### ISSUE TITLE
Missing Senate Section for 5/10 Congressional Record

### ISSUE THREAD

**Issue by jhanna71** [usgpo/api#102]
It appears that the Senate section for the 5/10 Congressional Record is missing. https://www.congress.gov/congressional-record

You can see the missing text starting on page 77 here. https://www.congress.gov/117/crec/2022/05/10/168/78/CREC-2022-05-10.pdf

**Comment by jhanna71** [comment]
Also the House section for the 5/10 Congressional Record just ends at page H4771 instead of continuing on until page H4800.

**Comment by jonquandt** [comment]
Hi -- this issue should now be resolved via the [govinfo API](https://api.govinfo.gov/packages/CREC-2022-05-10/summary?api_key=DEMO_KEY) and [UI](https://www.govinfo.gov/app/details/CREC-2022-05-10/context). It may take congress.gov a little time to update.

**Comment by jhanna71** [comment]
Thanks!
