### ISSUE TITLE
Missing Senate Section for 6/22 Congressional Record

### ISSUE THREAD

**Issue by jhanna71** [usgpo/api#105]
It appears that the Senate section for the 6/22 Congressional Record is missing. https://www.congress.gov/congressional-record

Also the House section for the 6/22 Congressional Record just ends at page H5808 instead of continuing on until page H5821.

**Comment by jonquandt** [comment]
Good morning. This appears to be fixed. I see the Senate section for this date as well as additional content in the House Section. 

https://api.govinfo.gov/packages/CREC-2022-06-22/summary?api_key=DEMO_KEY
