### ISSUE TITLE
Congressional Record for 12/15/2022 cut off at page H9902

### ISSUE THREAD

**Issue by jhanna71** [usgpo/api#110]
Congressional Record is cut off at page H9902
https://www.congress.gov/congressional-record/volume-168/issue-195/house-section/article/H9901-4

       H.R. 9601. A bill to ensure that homicides can be 
     prosecuted under Federal law without regard to the time 
     elapsed between the act or omission that caused the death of 
     the victim and the death itself; to the Committee on the 
     Judiciary.
           By Ms. UN

Compare with PDF
https://www.congress.gov/117/crec/2022/12/15/168/195/CREC-2022-12-15-pt1-PgH9901-4.pdf

**Comment by jonquandt** [comment]
We are investigating the issue.

**Comment by jonquandt** [comment]
This should now be resolved.
