### ISSUE TITLE
Enhancement Request - Individual Voting Records of Members

### ISSUE THREAD

**Issue by lezEngineer** [usgpo/api#115]
It would be helpful to have data on individual voting records per congressional member for all different voting events. It is also helpful to have the total votes on a bill, broken down with votes by party and the result of the legislation based on the vote. It would also be nice to corroborate that data between the senate and the house. 
If this data exists and I have not found it in the API please point me in the right direction.
Thank you.

**Comment by jonquandt** [comment]
GovInfo does provide access to roll call vote information as part of the Congressional Record, however, it may not be as directly accessible as other options

The best place to find such information is from the chambers themselves.

[Senate Vote data](https://www.senate.gov/legislative/votes_new.htm)
[House Vote Data](https://clerk.house.gov/Votes)

Each vote has an xml view. 

There are some open-source projects that have implemented scrapers for that data, you may wish to look for one of those.
