### ISSUE TITLE
Api Key Usage; Headers vs. query

### ISSUE THREAD

**Issue by BlankDev117** [usgpo/api#119]
This is more of a comment/question on the api key usage being a part of the query vs. a header request.
As a reference:
Some APIs use API keys for authorization. An API key is a special token that the client needs to provide when making API calls. The key is usually sent as a request header
https://swagger.io/docs/specification/2-0/authentication/api-keys/

This obviously isn't a hard-fast rule, but it's simply the way I'm used to handling api keys for my own personal projects and other professional works. https://api.congress.gov/ also seems to completely ignore this field if it is a header value

**Comment by jonquandt** [comment]
@BlankDev117 - Thanks for the feedback! You can send your key via header as well. In the documentation on the main readme, we do point out a link to api.data.gov on how to use your key via the **X-Api-key** header - which essentially mimics what's specified in the swagger documentation you linked.

The examples in the readme and in most issue discussions include the DEMO_KEY as a query parameter as a convenience for users.

Would you suggest that we update the readme to more clearly indicate that you can supply the key via a header value? Or are you suggesting a change to the interactive docs page?

**Comment by BlankDev117** [comment]
I did not see the link referencing this page https://api.data.gov/docs/api-key/

I simply looked at the readme and didn't dive deeper than that. Could potentially be  placed alongside the Keys section without the external link necessary and merely link the signup page from the readme. But, no big deal either. Thanks for the correction and my apologies for my misunderstanding.
