### ISSUE TITLE
Bad bill links being improperly parsed out from Supreme Court Cases and other text (U.S. 1850; 405 U.S. 1030)

### ISSUE THREAD

**Issue by jhanna71** [usgpo/api#121]
I noticed some bill links that were improperly parsed out from Supreme Court Cases and other text.

Some examples:

  Mr. Speaker, I include in the Record a timeline of the equal rights 
movement.

       1840:
       Lucretia Mott and Elizabeth Cady Stanton are barred from 
     attending the World Anti-Slavery Convention held in London. 
     They decide to hold a Women's Convention in the U.
<a href="/bill/118th-congress/senate-bill/1850">S.
--
  | 1850</a>:
       Massachusetts, is the site of the first National Women's 
     Rights Convention. Frederick Douglass, Paulina Wright Davis, 
     William Lloyd Garrison, Lucy Stone, and Sojourner Truth 
     attend. A strong alliance is formed with the Abolitionist 
     Movement.

https://www.congress.gov/congressional-record/volume-169/issue-55/house-section/article/H1456-5

See
--
  | also District of Columbia Federation of Civic Assn&#x27;s v.
  | Volpe, 459 F.2d 1231, 1265 (D.C. Cir. 1971), cert. denied,
  | 405 U.<a href="/bill/118th-congress/senate-bill/1030">S. 1030</a> (1972)

See 
     also District of Columbia Federation of Civic Assn&#x27;s v. 
     Volpe, 459 F.2d 1231, 1265 (D.C. Cir. 1971), cert. denied, 
     405 U.<a href="[/bill/118th-congress/senate-bill/1030](https://www.congress.gov/bill/118th-congress/senate-bill/1030)">S. 1030</a> (1972)

https://www.congress.gov/congressional-record/volume-169/issue-52/senate-section/article/S903-4

**Comment by llaplant** [comment]
Good afternoon. This issue seems to be more in scope for the Library of Congress - Congress.gov site instead of the Government Publishing Office - GovInfo.gov API. GPO passed this issue along our colleagues at the Library of Congress, but in the future you may want to explore Library of Congress GitHub repositories such as  https://github.com/LibraryOfCongress/api.congress.gov/issues.

**Comment by sscornelius** [comment]
<iframe width="560" height="315" src="https://www.youtube.com/embed/RAPaBuov9tk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
