### ISSUE TITLE
Missing Bill Text XML for BILLS-118hr3571ih and BILLS-118hres383eh

### ISSUE THREAD

**Issue by jhanna71** [usgpo/api#125]
Noticed that the Bill Text XML for BILLS-118hr3571ih and BILLS-118hres383eh are missing. Is there a way to get these online?

https://api.govinfo.gov/packages/BILLS-118hr3571ih/xml?api_key=API_KEY

https://api.govinfo.gov/packages/BILLS-118hres383eh/xml?api_key=API_KEY

Their HTML equivalents are available.

https://api.govinfo.gov/packages/BILLS-118hr3571ih/htm?api_key=API_KEY

https://api.govinfo.gov/packages/BILLS-118hres383eh/htm?api_key=API_KEY

**Comment by llaplant** [comment]
Thank you for bringing this to our attention. I am checking with upstream organizations on the availability of XML.

**Comment by jhanna71** [comment]
Also https://api.govinfo.gov/packages/BILLS-118hr4665rh/xml?api_key=API_KEY is missing.

**Comment by llaplant** [comment]
XML is available for https://www.govinfo.gov/content/pkg/BILLS-118hr4665rh/xml/BILLS-118hr4665rh.xml

**Comment by llaplant** [comment]
We are not expecting to receive XML for the two bills included in the original issue.

**Comment by sscornelius** [comment]
Hi,

**Comment by jhanna71** [comment]
Thanks. BILLS-118hr3496ih is missing XML too.

**Comment by llaplant** [comment]
We are not expecting to receive XML for BILLS-118hr3496ih
