### ISSUE TITLE
Govinfo API key

### ISSUE THREAD

**Issue by rammat10** [usgpo/api#136]
Hi there, 

I have not received my API key and would like to inquire about getting it. Thank you!

Account Email: email@email.com
Account ID: bf6913dd-8aca-4656-8cd1-8d4a006e3c7f

**Comment by jonquandt** [comment]
I have seen a similar issue related to another Federal API using the API.data.gov service. I am reaching out to the maintainers to see if they can investigate.

**Comment by warrenp94** [comment]
I also have not received a key yet...I sent a message via the contact form on the gov site.  I hesitate to include my email or account id here but can if necessary...just adding this comment to say there is a problem, not just specific to you it seems

**Comment by jonquandt** [comment]
@warrenp94 can you give a rough time when you signed up for a key to help troubleshoot?

**Comment by warrenp94** [comment]
It was somewhere around 8-9am EST on 11/11/2023

**Comment by jonquandt** [comment]
Good morning,

Please try creating a key again - the team supporting api.data.gov had an issue delivering emails over the weekend, but that is now resolved. 

https://github.com/18F/api.data.gov/issues/670#issuecomment-1808407109

**Comment by warrenp94** [comment]
@jonquandt - new email received with key...thanks for your help!
