### ISSUE TITLE
401 Errors

### ISSUE THREAD

**Issue by rammat10** [usgpo/api#137]
Dear GPO API Support Team,

I am developing a project that aims to leverage the GovInfo API to retrieve Congressional Records, which will then be processed through OpenAI's custom GPT builder.

I have encountered an issue with API access: consistently receiving a "401 API_KEY_INVALID" error when making requests to the API. This occurs even when testing through the Swagger UI.

Steps and details of my issue are as follows:
- Authenticated with my API key via Swagger UI.
- Made a GET request to the `/collections/CREC/{startDate}/{endDate}` endpoint.
- Replaced `{startDate}` and `{endDate}` with valid date values.
- Received a "401 API_KEY_INVALID" error in response.

I have verified that the API key is correct and active. I've also ensured there are no CORS or network-related issues at play. The request is formatted correctly, I think.

I am reaching out to seek your assistance in resolving this authentication problem. Your guidance would be invaluable in helping to advance my project.

Thank you for your support and looking forward to your response.

**Comment by jonquandt** [comment]
Can you provide a sample of one of your requests that is not working (excluding the actual key)?

Are you submitting your key via the header or via query parameter?

I am seeing some `collections/CREC` requests that are including the pageSize parameter twice or are missing some parameters. I wouldn't think that would cause a 401 API API_KEY_INVALID error. 

Doing some additional checking.

**Comment by jonquandt** [comment]
Here is a validly formatted collections request:
https://api.govinfo.gov/collections/CREC/2023-11-01T00:00:00Z?offsetMark=*&pageSize=100

This will return the most recently added or modified CREC packages since the beginning of November. 

I also saw a request like this:
`https://collections/CREC?offset=0&pageSize=1000&congress=103&congress=104&congress=105&congress=106&congress=107&congress=108&congress=109&congress=110&congress=111&congress=112&congress=113&congress=114&congress=115&congress=116&fields=packageId%2Ctitle%2CdateIssued%2CpdfLink&startDate=1993-01-01&endDate=2023-12-31`

This is not a validly formatted request.

You may want to try using our Search Service to make these requests. Something like:

```SHELL
curl -X 'POST' \
  'https://api.govinfo.gov/search?api_key=DEMO_KEY' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "query": "collection:CREC",
  "pageSize": 100,
  "offsetMark": "*",
  "sorts": [
    {
      "field": "lastModified",
      "sortOrder": "DESC"
    }
  ],
  "resultLevel": "package"
}'
```

will return a set of results that include the parameters that you are interested in (plus a few additional) - more info [here](https://curation.stage.govinfo.gov/features/search-service-overview) or the [Search Service quick start](https://github.com/usgpo/api#search-service)

**Comment by rammat10** [comment]
Hey Jon, thanks so much for the help and reply. I am still learning and I am extremely new to this. When you have a moment, I'd love your feedback here: 

`{
  "openapi": "3.0.0",
  "info": {
    "title": "Congressional Record Access via GovInfo API",
    "description": "This API interface retrieves Congressional Records from the GovInfo API for a specified date range.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://api.govinfo.gov"
    }
  ],
  "paths": {
    "/collections/CREC/{startDate}/{endDate}": {
      "get": {
        "summary": "Retrieve Congressional Records",
        "operationId": "getCongressionalRecords",
        "parameters": [
          {
            "name": "startDate",
            "in": "path",
            "required": true,
            "description": "The start date for retrieving records, in UTC format.",
            "schema": {
              "type": "string",
              "example": "1994-01-01T00:00:00Z"
            }
          },
          {
            "name": "endDate",
            "in": "path",
            "required": true,
            "description": "The end date for retrieving records, in UTC format.",
            "schema": {
              "type": "string",
              "example": "2023-11-13T23:59:59Z"
            }
          },
          {
            "name": "offsetMark",
            "in": "query",
            "required": false,
            "description": "The offset mark for pagination of results.",
            "schema": {
              "type": "string",
              "default": "*"
            }
          },
          {
            "name": "pageSize",
            "in": "query",
            "required": false,
            "description": "The number of results to return per request. Maximum is 100.",
            "schema": {
              "type": "integer",
              "default": 100,
              "maximum": 100
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response with Congressional Records data.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "packages": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "packageId": {
                            "type": "string"
                          },
                          "lastModified": {
                            "type": "string",
                            "format": "date-time"
                          },
                          "packageLink": {
                            "type": "string",
                            "format": "uri"
                          }
                        }
                      }
                    },
                    "nextPage": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request. The request was invalid."
          },
          "401": {
            "description": "Unauthorized. API key is missing or invalid."
          },
          "403": {
            "description": "Forbidden. The request is not allowed."
          },
          "404": {
            "description": "Not Found. The requested resource could not be found."
          },
          "500": {
            "description": "Internal Server Error. An error has occurred within the server."
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "x-api-key"
      }
    }
  },
  "security": [
    {
      "ApiKeyAuth": []
    }
  ]
}
`

**Comment by rammat10** [comment]
Hi Jon, thanks so much for getting back to me. I am very new at this so learning a lot. When you have a moment, I'd really appreciate your feedback here on what the issue is. 

{
  "openapi": "3.0.0",
  "info": {
    "title": "Congressional Record Access via GovInfo API",
    "description": "This API interface retrieves Congressional Records from the GovInfo API for a specified date range.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://api.govinfo.gov"
    }
  ],
  "paths": {
    "/collections/CREC/{startDate}/{endDate}": {
      "get": {
        "summary": "Retrieve Congressional Records",
        "operationId": "getCongressionalRecords",
        "parameters": [
          {
            "name": "startDate",
            "in": "path",
            "required": true,
            "description": "The start date for retrieving records, in UTC format.",
            "schema": {
              "type": "string",
              "example": "1994-01-01T00:00:00Z"
            }
          },
          {
            "name": "endDate",
            "in": "path",
            "required": true,
            "description": "The end date for retrieving records, in UTC format.",
            "schema": {
              "type": "string",
              "example": "2023-11-13T23:59:59Z"
            }
          },
          {
            "name": "offsetMark",
            "in": "query",
            "required": false,
            "description": "The offset mark for pagination of results.",
            "schema": {
              "type": "string",
              "default": "*"
            }
          },
          {
            "name": "pageSize",
            "in": "query",
            "required": false,
            "description": "The number of results to return per request. Maximum is 100.",
            "schema": {
              "type": "integer",
              "default": 100,
              "maximum": 100
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response with Congressional Records data.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "packages": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "packageId": {
                            "type": "string"
                          },
                          "lastModified": {
                            "type": "string",
                            "format": "date-time"
                          },
                          "packageLink": {
                            "type": "string",
                            "format": "uri"
                          }
                        }
                      }
                    },
                    "nextPage": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request. The request was invalid."
          },
          "401": {
            "description": "Unauthorized. API key is missing or invalid."
          },
          "403": {
            "description": "Forbidden. The request is not allowed."
          },
          "404": {
            "description": "Not Found. The requested resource could not be found."
          },
          "500": {
            "description": "Internal Server Error. An error has occurred within the server."
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "x-api-key"
      }
    }
  },
  "security": [
    {
      "ApiKeyAuth": []
    }
  ]
}

**Comment by rammat10** [comment]
Hey Jon, is this link broken? https://curation.stage.govinfo.gov/features/search-service-overview

**Comment by jonquandt** [comment]
This is the correct link - updated above. https://www.govinfo.gov/features/search-service-overview

**Comment by rammat10** [comment]
Hi Jon. 

Thanks for getting back to me. I am very new to this and coding in general so this is a learning process for sure, so I appreciate your help. When you have a moment, could you provide some feedback on the following? I appreciate the help on 'post' but as I understand this should get a 'Get' correct? 


```{
  "openapi": "3.0.0",
  "info": {
    "title": "Congressional Record Access via GovInfo API",
    "description": "This API interface retrieves Congressional Records from the GovInfo API for a specified date range.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://api.govinfo.gov/collections/CREC/1994-01-01T12%3A00%3A00Z/2023-11-11T12%3A00%3A00Z?pageSize=1000&offsetMark=%2A&api_key=PUT_API_KEY_HERE"
    }
  ],
  "paths": {
    "/collections/CREC/{startDate}/{endDate}": {
      "get": {
        "summary": "Retrieve Congressional Records",
        "operationId": "getCongressionalRecords",
        "parameters": [
          {
            "name": "startDate",
            "in": "path",
            "required": true,
            "description": "The start date for retrieving records, in UTC format.",
            "schema": {
              "type": "string",
              "example": "1994-01-01T00:00:00Z"
            }
          },
          {
            "name": "endDate",
            "in": "path",
            "required": true,
            "description": "The end date for retrieving records, in UTC format.",
            "schema": {
              "type": "string",
              "example": "2023-11-13T23:59:59Z"
            }
          },
          {
            "name": "offsetMark",
            "in": "query",
            "required": false,
            "description": "The offset mark for pagination of results.",
            "schema": {
              "type": "string",
              "default": "*"
            }
          },
          {
            "name": "pageSize",
            "in": "query",
            "required": false,
            "description": "The number of results to return per request. Maximum is 1000.",
            "schema": {
              "type": "integer",
              "default": 100,
              "maximum": 1000
            }
          },
          {
            "name": "api_key",
            "in": "query",
            "required": true,
            "description": "Your API key for the GovInfo API.",
            "schema": {
              "type": "string",
              "example": "sdxU6f2SG8juLQXv56pXZH8ZE4qZAnafeYEUOhOJ"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response with Congressional Records data.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "packages": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "packageId": {
                            "type": "string"
                          },
                          "lastModified": {
                            "type": "string",
                            "format": "date-time"
                          },
                          "packageLink": {
                            "type": "string",
                            "format": "uri"
                          }
                        }
                      }
                    },
                    "nextPage": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request. The request was invalid."
          },
          "401": {
            "description": "Unauthorized. API key is missing or invalid."
          },
          "403": {
            "description": "Forbidden. The request is not allowed."
          },
          "404": {
            "description": "Not Found. The requested resource could not be found."
          },
          "500": {
            "description": "Internal Server Error. An error has occurred within the server."
          }
        }
      }
    }
  },
  "components": {
    "schemas": {}
  }
}```

**Comment by rammat10** [comment]
Hi Jon. 

Thanks for getting back to me. I am very new to this and coding in general so this is a learning process for sure, so I appreciate your help. When you have a moment, could you provide some feedback on the following? I appreciate the help on 'post' but as I understand this should get a 'Get' correct? 


```{
  "openapi": "3.0.0",
  "info": {
    "title": "Congressional Record Access via GovInfo API",
    "description": "This API interface retrieves Congressional Records from the GovInfo API for a specified date range.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://api.govinfo.gov/collections/CREC/1994-01-01T12%3A00%3A00Z/2023-11-11T12%3A00%3A00Z?pageSize=1000&offsetMark=%2A&api_key=PUT_API_KEY_HERE"
    }
  ],
  "paths": {
    "/collections/CREC/{startDate}/{endDate}": {
      "get": {
        "summary": "Retrieve Congressional Records",
        "operationId": "getCongressionalRecords",
        "parameters": [
          {
            "name": "startDate",
            "in": "path",
            "required": true,
            "description": "The start date for retrieving records, in UTC format.",
            "schema": {
              "type": "string",
              "example": "1994-01-01T00:00:00Z"
            }
          },
          {
            "name": "endDate",
            "in": "path",
            "required": true,
            "description": "The end date for retrieving records, in UTC format.",
            "schema": {
              "type": "string",
              "example": "2023-11-13T23:59:59Z"
            }
          },
          {
            "name": "offsetMark",
            "in": "query",
            "required": false,
            "description": "The offset mark for pagination of results.",
            "schema": {
              "type": "string",
              "default": "*"
            }
          },
          {
            "name": "pageSize",
            "in": "query",
            "required": false,
            "description": "The number of results to return per request. Maximum is 1000.",
            "schema": {
              "type": "integer",
              "default": 100,
              "maximum": 1000
            }
          },
          {
            "name": "api_key",
            "in": "query",
            "required": true,
            "description": "Your API key for the GovInfo API.",
            "schema": {
              "type": "string",
              "example": "API_KEY_HERE"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response with Congressional Records data.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "packages": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "packageId": {
                            "type": "string"
                          },
                          "lastModified": {
                            "type": "string",
                            "format": "date-time"
                          },
                          "packageLink": {
                            "type": "string",
                            "format": "uri"
                          }
                        }
                      }
                    },
                    "nextPage": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request. The request was invalid."
          },
          "401": {
            "description": "Unauthorized. API key is missing or invalid."
          },
          "403": {
            "description": "Forbidden. The request is not allowed."
          },
          "404": {
            "description": "Not Found. The requested resource could not be found."
          },
          "500": {
            "description": "Internal Server Error. An error has occurred within the server."
          }
        }
      }
    }
  },
  "components": {
    "schemas": {}
  }
}```

**Comment by jonquandt** [comment]
@rammat10  - I don't understand where that openAPI spec is coming from. It's not the one we provide on the [GovInfo API docs ](https://api.govinfo.gov/govinfoapi/api-docs) page. 

If you are trying to submit a request with this:
`https://api.govinfo.gov/collections/CREC/1994-01-01T12%3A00%3A00Z/2023-11-11T12%3A00%3A00Z?pageSize=1000&offsetMark=%2A&api_key=PUT_API_KEY_HERE`
You need to replace `PUT_API_KEY_HERE` with your API KEY. Otherwise, you will get an API Key invalid.

https://api.govinfo.gov/collections/CREC/1994-01-01T12%3A00%3A00Z/2023-11-11T12%3A00%3A00Z?pageSize=1000&offsetMark=%2A&api_key=DEMO_KEY

if you are doing a /collections request, yes, you do need to do it as a GET. 

Note that the collections endpoint uses lastModified time, which is the time that content was added to or modified within GovInfo. If you are interested in restricting on date of publication (i.e. the Congressional Record issue date), the published endpoint could work for you as well. They return functionally identical content just with different means of specifying the results.

https://api.govinfo.gov/published/1993-01-01?offsetMark=*&collection=CREC&pageSize=100&api_key=DEMO_KEY

Can you confirm that either the collections or published links in this comment are working for you? It's unclear to me what specific request you are making to the GovInfo API.

**Comment by rammat10** [comment]
Hi Jon!

Following up and good news: we've successfully resolved the issues we were facing with the API integration. I greatly appreciate your guidance and support throughout this process. Here's a brief rundown of the issues we encountered and how we addressed them:

**API Key Invalid Error**: This was our primary hurdle. We found that the error was due to incorrect handling of the API key. Your suggestion to ensure the correct inclusion of the API key was crucial.

**OpenAPI Spec Misalignment**: We initially used a custom OpenAPI spec that didn't fully align with the official GovInfo API documentation. After reviewing your advice, we adjusted our OpenAPI specification to more accurately reflect the endpoints and parameters as outlined in the GovInfo API docs.

**API Key Handling - Header vs. Query**: We encountered an interesting challenge where the OpenAI setup expected the API key in the request header, whereas the GovInfo API required it as a query parameter. To address this, we implemented a dual approach in our system:

For GovInfo API calls, we continued using the query parameter method for the API key.
For OpenAI-related requests, we adapted our code to include the API key in the request header.

This dual approach allowed us to satisfy the authentication requirements of both APIs without compromising functionality or security.

Thank you once again for your assistance and patience. Your insights were invaluable in helping us navigate these challenges and learn along the way. After testing I'll share the link to the GPT with you in case you are interested!

-Matt

**Comment by jonquandt** [comment]
@rammat10 - I'm glad that I could resolve your issue. Note that you **can** pass the key for the GovInfo API via a header instead as a query parameter.

For more info on how to do that, see this [api.data.gov page](https://api.data.gov/docs/developer-manual/#api-key-usage)

The correct header is X-Api-Key

Example:

`curl -H 'X-Api-Key: DEMO_KEY' 'https://api.govinfo.gov/collections`
