### ISSUE TITLE
Missing Bill Text for S3621

### ISSUE THREAD

**Issue by jhanna71** [usgpo/api#143]
Looking for the Bill Text for S3621. Can you please tell me when it will become available?

https://www.congress.gov/bill/118th-congress/senate-bill/3621?s=1&r=1

**Comment by llaplant** [comment]
I am not able to provide a specific date, but I recommend checking back in a week.

**Comment by jhanna71** [comment]
Saw that the Bill Text for S3621 was available on Saturday, February 3rd. Thanks for looking into this.
