### ISSUE TITLE
An example of one of my requests:

### ISSUE THREAD

**Issue by abc1000200** [usgpo/api#145]
An example of one of my requests:
Fetching https://api.govinfo.gov/collections/CHRG/2019-01-01T00:00:00Z?pageSize=100&offset=0&api_key=<MY_API_KEY>

I traverse over all pages.

_Originally posted by @uwieske in https://github.com/usgpo/api/issues/61#issuecomment-605600138_

**Comment by jonquandt** [comment]
Closing this - please add this as a comment to #144 instead of creating a separate issue for the same situation.
