### ISSUE TITLE
What is the courtCode for Court of Federal Claims Opinions?

### ISSUE THREAD

**Issue by jspepper** [usgpo/api#146]
What is the correct courtCode for the Court of Federal Claims? I've tried both "cfc" and "cofc" and neither seems to work.

**Comment by jonquandt** [comment]
The courtCode should be `cofc`, but it appears that something in our API is not accepting that code. Looking into the issue.

In the mean-time, you could try the courtType=National to get those back. It will also return these courts

United States Court of International Trade
United States Judicial Panel on Multidistrict Litigation

**Comment by jonquandt** [comment]
The Search service is returning this ok, so the issue appears to be limited to the collections/published endpoints. Here's a sample curl request generated from our API documentation:

```shell
curl -X 'POST' \
  'https://api.govinfo.gov/search?api_key=DEMO_KEY' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "query": "collection:uscourts mods:courtCode:cofc",
  "pageSize": 10,
  "offsetMark": "*",
  "sorts": [
    {
      "field": "relevancy",
      "sortOrder": "DESC"
    }
  ],
  "historical": true,
  "resultLevel": "default"
}'
```

**Comment by jonquandt** [comment]
We will be implementing a fix for this in an upcoming release.

**Comment by jonquandt** [comment]
Good afternoon,

The issue has now been resolved - example link

https://api.govinfo.gov/collections/USCOURTS/2024-06-26T16:00:00Z?offsetMark=*&pageSize=100&api_key=DEMO_KEY&courtCode=cofc
