### ISSUE TITLE
https://api.govinfo.gov/packages/CHRG-111shrg54718/summary?api_key=DEMO_KEY throws an error

### ISSUE THREAD

**Issue by fgregg** [usgpo/api#15]
visiting https://api.govinfo.gov/packages/CHRG-111shrg54718/summary?api_key=DEMO_KEY

returns this error page:

![screenshot_2018-10-03 https api govinfo gov](https://user-images.githubusercontent.com/536941/46419050-a0fb2900-c6f2-11e8-9d85-a320707d7ae3.png)

**Comment by fgregg** [comment]
Also: 

- https://api.govinfo.gov/packages/CHRG-111shrg48299/summary?api_key=DEMO_KEY

**Comment by jonquandt** [comment]
@fgregg - this should be fixed now.

**Comment by fgregg** [comment]
https://api.govinfo.gov/packages/CHRG-111shrg54718/summary?api_key=DEMO_KEY is throwing an error again.

**Comment by jonquandt** [comment]
Fixed again! looks like we hadn't fully synced our configurations to our secondary site. That's been fixed.
