### ISSUE TITLE
missing html and pdf download links for CHRG collection at summary link

### ISSUE THREAD

**Issue by relarson1** [usgpo/api#16]
Hi all seems like CHRG collection is missing the html and pdf download links at the summary level 

https://api.govinfo.gov/packages/CHRG-111shrg54718/summary?api_key=DEMO_KEY

```

"title": "THE DISCOUNT PRICING CONSUMER PROTECTION ACT: DO WE NEED TO RESTORE THE BAN ON VERTICAL PRICE FIXING?",
"collectionCode": "CHRG",
"collectionName": "Congressional Hearings",
"category": "Congressional Committee Materials",
"dateIssued": "2009-05-19",
"detailsLink": "https://www.govinfo.gov/app/details/CHRG-111shrg54718",
"granulesLink": "https://api.govinfo.gov/packages/CHRG-111shrg54718/granules?offset=0&pageSize=100",
"packageId": "CHRG-111shrg54718",
"download": {
"modsLink": "https://api.govinfo.gov/packages/CHRG-111shrg54718/mods",
"premisLink": "https://api.govinfo.gov/packages/CHRG-111shrg54718/premis",
"zipLink": "https://api.govinfo.gov/packages/CHRG-111shrg54718/zip"
},

```

shouldn't there be html and pdf download links in there?   like on 
https://www.govinfo.gov/app/details/CHRG-111shrg54718/CHRG-111shrg54718/summary

**Comment by jonquandt** [comment]
@relarson1 The details link you have at the bottom is for a granule of the hearing. The equivalent details link for the package level is: 
https://www.govinfo.gov/app/details/CHRG-111shrg54718 

Congressional Hearings package-level summaries only include:
- mods for the package
- premis for the package
- zip of all content and metadata

The PDF and HTML of hearings are available at the granule level. This is the case even for hearings that only have a single granule. 

The pdf and html for this particular hearing are available on the granule summary page:
https://api.govinfo.gov/packages/CHRG-111shrg54718/granules/CHRG-111shrg54718/summary?api_key=DEMO_KEY

```json
{
	"title": "The Discount Pricing Consumer Protection Act: Do We Need to Restore the Ban on Vertical Price Fixing?",
	"collectionCode": "CHRG",
	"collectionName": "Congressional Hearings",
	"category": "Congressional Committee Materials",
	"dateIssued": "2009-05-19",
	"detailsLink": "https://www.govinfo.gov/app/details/CHRG-111shrg54718/CHRG-111shrg54718",
	"granulesLink": "https://api.govinfo.gov/packages/CHRG-111shrg54718/granules?offset=0&pageSize=100",
	"packageId": "CHRG-111shrg54718",
	"packageLink": "https://api.govinfo.gov/packages/CHRG-111shrg54718/summary",
	"granuleId": "CHRG-111shrg54718",
	"download": {
		"txtLink": "https://api.govinfo.gov/packages/CHRG-111shrg54718/granules/CHRG-111shrg54718/htm",
		"pdfLink": "https://api.govinfo.gov/packages/CHRG-111shrg54718/granules/CHRG-111shrg54718/pdf",
		"modsLink": "https://api.govinfo.gov/packages/CHRG-111shrg54718/granules/CHRG-111shrg54718/mods",
		"premisLink": "https://api.govinfo.gov/packages/CHRG-111shrg54718/premis",
		"zipLink": "https://api.govinfo.gov/packages/CHRG-111shrg54718/zip"
	},
	"granuleClass": "OTHERPART",
	"graphicsInPDF": "true",
	"isAppropriation": "false",
	"lastModified": "2018-07-30T19:41:21Z"
}
```


Here's an example of a package with multiple granules:

House Hearing, 115th Congress - THE NEXT FARM BILL
CHRG-115hhrg24725
[details](https://www.govinfo.gov/app/details/CHRG-115hhrg24725/CHRG-115hhrg24725-pt2/context)
[api package summary](https://api.govinfo.gov/packages/CHRG-115hhrg24725/summary?api_key=DEMO_KEY)

[granule list](https://api.govinfo.gov/packages/CHRG-115hhrg24725/granules?offset=0&pageSize=10&api_key=DEMO_KEY)

```json
{
	"count": 2,
	"offset": 0,
	"pageSize": 100,
	"nextPage": null,
	"previousPage": null,
	"granules": [{
			"title": "The Next Farm Bill",
			"granuleId": "CHRG-115hhrg24725-pt1",
			"granuleLink": "https://api.govinfo.gov/packages/CHRG-115hhrg24725/granules/CHRG-115hhrg24725-pt1/summary"
		}, {
			"title": "Farm Bill Listening Sessions: Conversations in the Field",
			"granuleId": "CHRG-115hhrg24725-pt2",
			"granuleLink": "https://api.govinfo.gov/packages/CHRG-115hhrg24725/granules/CHRG-115hhrg24725-pt2/summary"
		}
	]
}
```

[granule summary](https://api.govinfo.gov/packages/CHRG-115hhrg24725/granules/CHRG-115hhrg24725-pt1/summary?api_key=DEMO_KEY)

hope that's helpful - let me know if you need some additional info.

**Comment by relarson1** [comment]
Thanks! that is helpful I'll pass this along to the developer.
