### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by iita-atii** [usgpo/api#161]
Is there any full documentation available for the resources available in the [bulk data repository](https://www.govinfo.gov/bulkdata)? Looking for something similar to what's provided by the [congressional API](https://github.com/LibraryOfCongress/api.congress.gov/tree/main/Documentation) or the [Congress IO project](https://github.com/unitedstates/congress/wiki).

Also, is there a ZIP available to download of the contents of bulk data collections? I'd like to avoid burning through all my API request.

**Comment by jonquandt** [comment]
@iita-atii  - look at our [bulk-data repository](https://github.com/usgpo/bulk-data/), which includes user guides for some of the bulkdata collections. We also have additional documentation specifically for the BILLSTATUS content in the [bill-status repository](https://github.com/usgpo/bill-status/)

There is no single zip file to download all of the bulkdata for a given collection, but there are usually ZIP files available at slightly lower levels that will aggregate information. For example, for the BILLS collection, you could go to a congress/session/billtype page and grab the zip file to get all of the bills of that type for the given congress/session.

https://www.govinfo.gov/bulkdata/BILLS/118/1/hconres
https://www.govinfo.gov/bulkdata/BILLS/118/1/hconres/BILLS-118-1-hconres.zip
