### ISSUE TITLE
API is down?

### ISSUE THREAD

**Issue by fgregg** [usgpo/api#17]
Hi, the API seems to be down. Is there a status page or mailing list to get notified of outages?

Thanks!

**Comment by jonquandt** [comment]
@fgregg - working on a fix. I'll send an update when it's back up.

**Comment by jonquandt** [comment]
API access is restored. We're still working on stabilizing things, and I'll add some processes for future issues to ensure folks are notified in the future, even for unexpected downtime like this.

**Comment by fgregg** [comment]
Thanks!
