### ISSUE TITLE
support congress as a top level searchable element in the API

### ISSUE THREAD

**Issue by relarson1** [usgpo/api#20]
For many of the collections they are congress specific and in the package info they have the congress in them 
for example the bills collection:
package level has:"congress": "115",
but at the collection level that information is not available:
https://api.govinfo.gov/collections/BILLS/2018-01-01T00:00:00Z?offset=0&pageSize=10&api_key=

> 
> "packageId": "BILLS-115hr609enr",
> "lastModified": "2018-11-01T14:59:34Z",
> "packageLink": "https://api.govinfo.gov/packages/BILLS-115hr609enr/summary",
> "docClass": "hr",
> "title": "An Act T

It would be very helpful for  downloading to allow searching and filtering by congress at the collection level, similar to how docClass was added for the CDOC collection
i.e. 
https://api.govinfo.gov/collections/BILLS/2018-01-01T00:00:00Z?offset=0&pageSize=10&congress=115&api_key=
and return only 115th items for that time period.

**Comment by jonquandt** [comment]
This is now available. Note that for the following collections, we are performing some reindexing to get the congress values to appear at the package level:

CREC
ECONI
HJOURNAL
HMAN
HOB
SMAN
STATUTE

This republishing will take some time (several weeks), and we will be focusing on the most recent documents. New content in these collections will have the Congress values as soon as they are initially
