### ISSUE TITLE
crec for days with multiple issues (start of new congresses)

### ISSUE THREAD

**Issue by relarson1** [usgpo/api#23]
For the  CREC collection at the start of the new congress there are usually 2 issues, what is the api url to distinguish between congresses:

i.e.
https://api.govinfo.gov/packages/CREC-2019-01-03/mods
is that for 116th or 115th?

I see that https://www.govinfo.gov/app/details/CREC-2019-01-03/summary
says it is the 116th congress, but the volume 164 issue 208 is for the previous 115th congress as are the pdfs.

**Comment by llaplant** [comment]
Hi @relarson1 CREC MODS metadata is not available for an individual CREC book, but it is available at the package level (issue) and granule level (document). We can look at a potential future enhancement to the API if CREC metadata is refactored to add metadata for a book.

**Comment by relarson1** [comment]
Well the metadata for the 2019/1/3 book 1 are incorrect in the api and mods file.  Hopefully a future enhancement will  correct them so that granules contents (bills referenced in the extension of remarks) correctly correspond to the congress they belong to : 
  for example:
granules in the 115th (book1) in the api report as being part of the 116th congress, 
https://api.govinfo.gov/packages/CREC-2019-01-03/granules/CREC-2019-01-03-pt1-PgE1745-2/summary?api_key=DEMO_KEY

when they really should be referring to the 115th congress.
```
"title": "PERSONAL EXPLANATION",
"collectionCode": "CREC",
"collectionName": "Congressional Record",
"category": "Proceedings of Congress and General Congressional Publications",
"dateIssued": "2019-01-03",
"detailsLink": "https://www.govinfo.gov/app/details/CREC-2019-01-03/CREC-2019-01-03-pt1-PgE1745-2",
"granulesLink": "https://api.govinfo.gov/packages/CREC-2019-01-03/granules?offset=0&pageSize=100",
"packageId": "CREC-2019-01-03",
"packageLink": "https://api.govinfo.gov/packages/CREC-2019-01-03/summary",
"granuleId": "CREC-2019-01-03-pt1-PgE1745-2",
"download": {
"txtLink": "https://api.govinfo.gov/packages/CREC-2019-01-03/granules/CREC-2019-01-03-pt1-PgE1745-2/htm",
"pdfLink": "https://api.govinfo.gov/packages/CREC-2019-01-03/granules/CREC-2019-01-03-pt1-PgE1745-2/pdf",
"modsLink": "https://api.govinfo.gov/packages/CREC-2019-01-03/granules/CREC-2019-01-03-pt1-PgE1745-2/mods",
"premisLink": "https://api.govinfo.gov/packages/CREC-2019-01-03/premis",
"zipLink": "https://api.govinfo.gov/packages/CREC-2019-01-03/zip"
},
"bookNumber": "1",
"granuleClass": "EXTENSIONS",
"subGranuleClass": "PERSONALEXPLAIN",
"granuleDate": "2019-01-03",
"pagePrefix": "E",
"references": [
{
"collectionCode": "BILLS",
"collectionName": "Congressional Bills",
"contents": [
{
"congress": "116",
"type": "HR",
"number": "88"
},
[...]
```

mods.xml fragment:
```
<extension>
<searchTitle>PERSONAL EXPLANATION; Congressional Record Vol. 164, No. 208</searchTitle>
<granuleClass>EXTENSIONS</granuleClass>
<accessId>CREC-2019-01-03-pt1-PgE1745-2</accessId>
<subGranuleClass>PERSONALEXPLAIN</subGranuleClass>
<pagePrefix>E</pagePrefix>
<bookNumber>1</bookNumber>
<chamber>HOUSE</chamber>
<granuleDate>2019-01-03</granuleDate>
<bill congress="116" context="OTHER" number="88" type="HR"/>
<bill congress="116" context="OTHER" number="695" type="HR"/>
<bill congress="116" context="OTHER" number="1934" type="S"/>
<bill congress="116" context="OTHER" number="2322" type="S"/>
<bill congress="116" context="OTHER" number="7388" type="HR"/>
<congMember authorityId="1498" bioGuideId="K000188" chamber="H" congress="116" gpoId="8216" party="D" role="SPEAKING" state="WI">
<name type="parsed">Mr. KIND</name>
<name type="authority-fnf">Ron Kind</name>
<name type="authority-lnf">Kind, Ron</name>
</congMember>
</extension>
```
thanks

**Comment by jonquandt** [comment]
@relarson1  -- I believe this has been addressed in a recent release, as we are now distinguishing between CRECs on the same day in different sessions or congresses by appending a volume number to the packages.

For example, 
CREC-2019-01-03 has been split into two packages:

- https://api.govinfo.gov/packages/CREC-2019-01-03-v164/summary 
- https://api.govinfo.gov/packages/CREC-2019-01-03-v165/summary 

Code to fix this was released in December 2019, and we went back and updated the packages that were previously affected by this as part of operational work during this release.
