### ISSUE TITLE
Bills missing from bills collection?

### ISSUE THREAD

**Issue by showerst** [usgpo/api#26]
(This is as of Jan 23, 2:45pm eastern) If I hit the bills collection endpoint for all bills since 2019-01-01

`
https://api.govinfo.gov/collections/BILLS/2019-01-01T20%3A18%3A10Z?offset=0&pageSize=1000&api_key=<my key>
`

It seems to be missing a number of senate bills, for example [s158](https://www.govinfo.gov/bulkdata/BILLSTATUS/116/s/BILLSTATUS-116s158.xml). The bill was clearly created/updated since 2019-01-01.

What should I be doing to get all bills from that endpoint?

**Comment by jonquandt** [comment]
This is a data availability issue. The text for s158 isn't in govinfo yet -- there are some instances (particularly for introduced bills), where there is a lag between the billstatus and the billtext becoming available.

**Comment by showerst** [comment]
Thanks @jonquandt -- The bill XML hits [billstatus-bulkdata.xml](https://www.govinfo.gov/rss/billstatus-bulkdata.xml) before it enters the API, right? I'm trying to find the fastest way(s) to get both the metadata and the billtext into my system.

**Comment by jonquandt** [comment]
@showerst - I haven't monitored it closely enough to be assured of that in all cases, but I think that is likely for introduced bills. For some other versions of bills, I do believe that the text can become available via the API prior to the billstatus update.

I'll see what I can find out.

**Comment by showerst** [comment]
@jonquandt thanks! Even clarification on what piece hits what system first is helpful, or the triggers if it's inconsistent.

**Comment by asebold** [comment]
Curious if you guys could elaborate on what causes the delay in information? I've noticed some votes and actions missing by a few days as well.

**Comment by jonquandt** [comment]
We have two different data partners that provide the source data for BILLS and BILLSTATUS.

The bill text (BILLS packages) are provided by Congress and are composed, proofed, and ingested into **govinfo** as part of GPO's publishing process. BILLSTATUS information is provided by the Library of Congress.

Depending on a particular status step, the BILLSTATUS file (which contains metadata about a legislative measure as a whole) or the BILLS package (content and metadata for a specific bill version) may be updated first. 

To clarify -- BILLS XML files should be available via the bulkdata repository and the govinfo API at the same time.

BILLSTATUS file updates occur in batches approximately every four hours, per the [billstatus readme](https://github.com/usgpo/bill-status/blob/master/README.md), whereas bills are added throughout the day as they become available, though primarily in the evening and overnight hours. 

BILLS-116s158is is available via the API: 
https://api.govinfo.gov/collections/BILLS/2019-01-01T00:00:00Z?offset=100&pageSize=100&congress=116&docClass=s&api_key=DEMO_KEY 

https://api.govinfo.gov/packages/BILLS-116s158is/summary?api_key=DEMO_KEY 

and 
Bulkdata
https://www.govinfo.gov/bulkdata/BILLS/116/1/s/BILLS-116s158is.xml

Let me know if there is anything I can clarify.
