### ISSUE TITLE
FR issue granules (granule content) in XML format

### ISSUE THREAD

**Issue by nirmalapudota** [usgpo/api#28]
Hi Team,

I am looking for an efficient way to get the  content/section numbers/amendment details of selected granules of a FR issue.  The XML structure of FR issues provides this information, but it is at entire issue level. Is there a way to get the XML format file  at a granule level as well.  Right now, I see that the granules data (the content) is available in pdf and htm formats.

e.g., package FR-2019-01-23, I can get the entire issue with this api call: https://api.govinfo.gov/packages/FR-2019-01-23/xml?api_key=DEMO_KEY, 
in this if I am interested only the granule “2019-00089” and section numbers and amendment details mentioned in it, I had to search for the granule ID in the XML and take the help of XML tree structure (which is <Rule>, <Section> and <AMDPAR> tags) to get the required content that I am looking for. 

I am wondering if the XML structure of the granules are available separately, like how htm and pdf version are given:  https://api.govinfo.gov/packages/FR-2019-01-23/granules/2019-00089/htm?api_key=DEMO_KEY
"download":{"txtLink":"https://api.govinfo.gov/packages/FR-2019-01-23/granules/2019-00089/htm","pdfLink":"https://api.govinfo.gov/packages/FR-2019-01-23/granules/2019-00089/pdf","modsLink":"https://api.govinfo.gov/packages/FR-2019-01-23/granules/2019-00089/mods","premisLink":"https://api.govinfo.gov/packages/FR-2019-01-23/premis","zipLink":"https://api.govinfo.gov/packages/FR-2019-01-23/zip"}

If  there are any alternative ways to get FR granule level content/specific section numbers of a granule from API rather taking XML file , please suggest.

Thank you
Nirmala

**Comment by jonquandt** [comment]
There is currently no official xml rendition for individual granules available via govinfo at this time.

You may want to look at the federal register.gov API, which can return enhanced json and xml for FR documents.

Here is a call that will return the link to the xml.

www.federalregister.gov/api/v1/documents/2019-00089.json?fields%5B%5D=full_text_xml_url

The FR2.0 API has interactive documentation available here:

https://www.federalregister.gov/reader-aids/developer-resources/rest-api

**Comment by nirmalapudota** [comment]
this is very helpful. thank you.
