### ISSUE TITLE
Request for LSA section level info in JSON or XML format

### ISSUE THREAD

**Issue by nirmalapudota** [usgpo/api#31]
Hi Team,

LSA collection provides list of CFR sections affected. I was able to get the granules links that provides Title level information e.g., API call that provides granules in LSA collection published in Jan-2019: https://api.govinfo.gov/packages/LSA-2019-01/granules?offset=0&pageSize=100&api_key=DEMO_KEY
From the above link, using the ‘granuleLink’,  I could get summary info for each title. (e.g., API link: https://api.govinfo.gov/packages/LSA-2019-01/granules/LSA-2019-01-title20/summary?api_key=DEMO_KEY). 
from this summary link, in order to get the details of the sections effected, I think I need to look at pdf and htm format links ("txtLink" and "pdfLink"). E.g., htm format link: https://api.govinfo.gov/packages/LSA-2019-01/granules/LSA-2019-01-title20/htm?api_key=DEMO_KEY; and pdfLink: https://api.govinfo.gov/packages/LSA-2019-01/granules/LSA-2019-01-title20/pdf?api_key=DEMO_KEY

Could you let me know if the sections effected information is available through XML or JSON? I would like to consolidate each section that got affected separately, e.g., write each section that got affected to a single row in csv file.
This kind of manipulation on the PDF and HTM format seems complex, rather not possible as am not able to set demarcation between the section numbers start and end in the HTML format.
Please suggest if I am missing to get the right API link in order to get the section level info in easy manipulation or machine readable format.

Thank you 
Nirmala

**Comment by jonquandt** [comment]
@nirmalapudota - currently we do not have XML or json versions of the sections affected within the LSA collection.  If that becomes available within the data itself, we would expose it in the API. 

Alternatively, you can look at what we've done with the CFR Parts Affected functionality on the UI. That information is based directly on the Federal Register documents, so it's updated more frequently. Once we have the #1 built, it would likely be best to construct queries there to get the information you are looking for.

This actually might be another useful service to create in the govinfo API.

**Comment by jonquandt** [comment]
Another thought would be to take a look at the eCFR, which is an editorial compilation of CFR material and amendments published in the daily Federal Register. It has unofficial status, but it could be useful for what you are looking for. 

https://www.ecfr.gov/cgi-bin/text-idx?tpl=%2Findex.tpl

We also make the ECFR available via our bulkdata repository, and as of last week, the API.

e.g. 
https://www.govinfo.gov/bulkdata/json/ECFR

https://api.govinfo.gov/collections/ECFR/2019-04-01T00:00:00Z?offset=0&pageSize=100&api_key=DEMO_KEY
- this would let you know which CFR titles have been updates in the eCFR, which could potentially be used as a proxy at a high-level (ECFR is updated at the title level in our bulkdata/API) for which parts have had changes.
