### ISSUE TITLE
Agency Mapping for Section or Each Granule 

### ISSUE THREAD

**Issue by Aniformer** [usgpo/api#40]
Hi team, 

The ECFR website provides us with the regulatory entity mapping for each Title and Volume. Is their any API endpoint or source from which we can obtain this information in machine readable format? The ecfr link we are referring to is here :  https://www.ecfr.gov/cgi-bin/ECFR?page=browse

For eg --
CFR-2018-title17-vol1-sec1-2, this particular granuleID is present in the below API endpoint : 
https://api.govinfo.gov/packages/CFR-2018-title17-vol1/granules?offset=0&pageSize=10000&api_key=NSlyx6Yi2AMkeRUpQKm4YFgRSupyXNcobKsKUbGT

We need to map each granuleID present in the above API endpoint with the regulatory entities present on the ECFR website.  Any insight would be appreciated! 

Thank you, 
Anirudh

**Comment by llaplant** [comment]
@Aniformer you may want to look at eCFR XML Bulk Data. 
It is available at https://www.govinfo.gov/bulkdata/ECFR
