### ISSUE TITLE
Title 12 volume 2 and volume 5 data not available.

### ISSUE THREAD

**Issue by manimittal15** [usgpo/api#42]
Hi Team,

While checking for 2019 data for title 12 we found it is missing for volume 2 and volume 5. I have mentioned the API calls below. Please let us know when the data will be available.

Also please let us know if there will be any change in data already available and how to track those changes. 
Please do let us know the timelines for uploading 2019 data for remaining titles as well.

https://api.govinfo.gov/packages/CFR-2019-title12-vol2/granules?offset=0&pageSize=10000&api_key=DEMO_KEY
https://api.govinfo.gov/packages/CFR-2019-title12-vol5/granules?offset=0&pageSize=10000&api_key=DEMO_KEY

Thanks,
Mani Mittal

**Comment by jonquandt** [comment]
@manimittal15 

On govinfo, the [Code of Federal Regulations](https://www.govinfo.gov/app/collection/CFR) (CFR) is current with the published print version of the CFR. When the print editions are released, the online version is also made available. If a CFR Title or volume is not listed in the CFR browse, that volume has not been published at that time. The date for which a particular Title of the CFR is published varies with each Title and volume and is dependent upon the publisher. The Code of Federal Regulations is published by the Office of the Federal Register, National Archives and Records Administration.

In general, CFR volumes are updated (not published) once each calendar year, on a staggered basis in accordance with the annual update cycle. The annual update cycle is as follows: Titles 1-16 are updated as of January 1st; Titles 17-27 are updated as of April 1st; Titles 28-41 are updated as of July 1st; Titles 42-50 are updated as of October 1st.

You can track when these become available by continuing to use the [CFR collections endpoint](https://api.govinfo.gov/collections/CFR/2019-05-01T00:00:00Z?offset=0&pageSize=100&api_key=DEMO_KEY) or subscribing to the [CFR RSS feed](https://www.govinfo.gov/rss/cfr.xml).

As an alternative resource, the [Electronic Code of Federal Regulations](https://www.ecfr.gov/cgi-bin/ECFR?page=browse) (eCFR), is a currently updated version of the CFR. It is not an official legal edition of the CFR. The e-CFR is an editorial compilation of CFR material and Federal Register amendments produced by the National Archives and Records Administration's Office of the Federal Register (OFR) and the Government Publishing Office. The OFR updates the material in the e-CFR on a daily basis. The eCFR is available on govinfo via our [bulkdata repository](https://www.govinfo.gov/bulkdata/ECFR) and the [API](https://api.govinfo.gov/collections/ECFR/2019-05-21T00:00:00Z?offset=0&pageSize=100&api_key=DEMO_KEY)

**Comment by jonquandt** [comment]
@manimittal15 - just a note that I'm going to close this issue as it's not related to the API itself, but general availability of data.

**Comment by manimittal15** [comment]
Hi Team,
Could you please let us know if there is any link/source where we can track for the release of print editions of CFR volumes.

Thanks,
Mani Mittal
