### ISSUE TITLE
Title 12 2018 API showing last modified date as 2019-05-06

### ISSUE THREAD

**Issue by manimittal15** [usgpo/api#43]
Hi Team,

I have recently extracted the Title 12 API Data for 2018 (CFR-2018-title12-vol1). That time it was showing last modified date as 2018-08-03. Since new data is available for 2019 but 2018 API is also showing last modified date as 2019-05-06. Does this means metadata for 2018 is also changed and I need to extract the 2018 data again. 
Sample API : https://api.govinfo.gov/packages/CFR-2018-title12-vol1/granules/CFR-2018-title12-vol1-chapI-toc-id4/summary?api_key=DEMO_KEY

Please look into the issue and suggest.

Thanks and regards,
Mani Mittal

**Comment by jonquandt** [comment]
@manimittal15 - the collections service will list packages that have been added or updated within the time frame specified. The json summary for a given package and granule will report this same `lastModified` time. 

This follows the same convention as seen in our sitemaps. this could just mean a reprocessing to fix a metadata issue or a complete replacement of the package. I would recommend reextracting that data if you want to always have the latest version.

**Comment by manimittal15** [comment]
Thank you very much Jon. This helps.
