### ISSUE TITLE
Request: Get page range of sections/parts in CFR

### ISSUE THREAD

**Issue by nirmalapudota** [usgpo/api#44]
Hi Team,

Could you suggest if there is way to get pageNumbers or range of pages for each part or chapter or section in CFR Titles. 
E.g., This is the PDF of  "Subpart A" in Title12/Part3. It starts at Page 17 and go until Page 41 and total of 25pages
https://api.govinfo.gov/packages/CFR-2018-title12-vol1/granules/CFR-2018-title12-vol1-part3-subpartA/pdf?api_key=DEMO_KEY;
Similarly for a section 1.110,  it starts and ends in Page 13 with total of 1 page.
https://api.govinfo.gov/packages/CFR-2018-title12-vol1/granules/CFR-2018-title12-vol1-sec1-110/pdf?api_key=DEMO_KEY

i looked at the corresponding mods XML also Premis XML. I was not able to find this info anywhere.   It would be very helpful if there is a way to get this info from API.

Thank you
Nirmala

**Comment by jonquandt** [comment]
@nirmalapudota - generally, CFR citations are based on the part/chapter/section. Within Mods, the following leafRange element includes the section range.

https://api.govinfo.gov/packages/CFR-2018-title12-vol1/granules/CFR-2018-title12-vol1-part3-subpartA/mods?api_key=DEMO_KEY

`<partRange from="3" to="3" /><leafRange from="§ 3.1" to="§§ 3.4-3.9" type="section" />`

We don't parse metadata for the CFR from PDF, so we don't have that information available within the package.

**Comment by nirmalapudota** [comment]
thank you.
