### ISSUE TITLE
Question: USCOURTS Total Package Count Variance

### ISSUE THREAD

**Issue by tommyball** [usgpo/api#45]
Hi,
Quick question, I've just started looking into the API specificity for the US COURTS.
When you call the collection endpoint: 
https://api.govinfo.gov/collections?api_key=XXXX
It returns the package and granule count for each collection. 

The USCOURTS Collection has a package count `of:` 3,801,046
 {
            "collectionCode": "USCOURTS",
            "collectionName": "United States Courts Opinions",
            **"packageCount": 3801046,**
            "granuleCount": 2617554
        }``

Now when I call the USCOURTS collections endpoint: 
https://api.govinfo.gov/collections/USCOURTS/1990-01-01T20%3A18%3A10Z?offset=0&pageSize=10000&api_key=XXXXXX

I get back a total count of 1,184,518
`{
    "count": 1184518,
    "message": null,
    "nextPage": "https://api.govinfo.gov/collections/USCOURTS/1990-01-01T20:18:10Z?offset=10000&pageSize=10000",
    "previousPage": null,
    "packages": []
}`

I've tried change the date and no matter what I change it to this is the maximum total packages available.  

So is the total packageCount from the collection the real total or not? 

If so how do I obtain the rest of the packages when I invoke the USCOURTS collection api call? 

Thank you.

**Comment by jonquandt** [comment]
@tommyball -- there appears to be an issue with the packageCount displayed for USCOURTS in the basic /collections request. The ~1.2M package count listed in the specific USCOURTS request matches what is in the system. 

We're going to fix the query for the base collections request. 

Please let me know if you have any more feedback on USCOURTS collections requests.

**Comment by tommyball** [comment]
@jonquandt Thank you for the update. I will let you know if I come across anything else.

**Comment by jonquandt** [comment]
This should be resolved at this time. 

`"collectionName":"United States Courts Opinions","packageCount":1198697,"granuleCount":2647764}`

matches number of results in the [general search for USCOURTS packages](https://www.govinfo.gov/app/search/%7B%22query%22%3A%22collection%3Auscourts%22%2C%22offset%22%3A0%7D)
