### ISSUE TITLE
Query specific data from large collection?

### ISSUE THREAD

**Issue by BigRoofus** [usgpo/api#47]
Is it possible to query specific data from the § 172.101 Hazardous Materials Table in the Code of Federal Regulations?
https://www.govinfo.gov/app/details/CFR-2018-title49-vol2/CFR-2018-title49-vol2-sec172-101/summary

For example if I wanted to get the info related to the Identification Number UN1088, such as Hazardous materials descriptions and proper shipping names, Hazard class or Division, Identification Numbers, PG, Label Codes, Special provisions, and Packaging Exceptions, how would I construct my CURL query?  (please see this image for clarification https://imgur.com/a/OpXuMf1)

Thank you.

**Comment by jonquandt** [comment]
@BigRoofus - the way to do this would be to grab the xml from the following link:

https://api.govinfo.gov/packages/CFR-2018-title49-vol2/granules/CFR-2018-title49-vol2-sec172-101/xml?api_key=DEMO_KEY

and then use XPath or similar to query the information from the file itself. The information is available starting in line 332. 

```xml
      <ROW>
        <ENT I="01"/>
        <ENT>Acetal</ENT>
        <ENT>3</ENT>
        <ENT>UN1088</ENT>
        <ENT>II</ENT>
        <ENT>3</ENT>
        <ENT>IB2, T4, TP1</ENT>
        <ENT>150</ENT>
        <ENT>202</ENT>
        <ENT>242</ENT>
        <ENT>5 L</ENT>
        <ENT>60 L</ENT>
        <ENT>E</ENT>
      </ROW>
```

The API itself does not support querying at the level you're looking for at this time.
