### ISSUE TITLE
Where can we see subject terms associated with bills in API?

### ISSUE THREAD

**Issue by manimittal15** [usgpo/api#50]
Hi Team,

On congress.gov we can view Subject Terms assigned to bills ( link : https://www.congress.gov/bill/116th-congress/house-bill/1839/subjects?overview=closed ). Could you please tell where can we see the same information in bills API.

Thanks,
Mani Mittal

**Comment by jonquandt** [comment]
Thanks for the question- you can get the same information from our BILLSTATUS files available via both bulkdata and the api

https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr1839.xml

https://api.govinfo.gov/packages/BILLSTATUS-116hr1839/summary?api_key=DEMO_KEY

**Comment by manimittal15** [comment]
@jonquandt thank you for the answer. I am getting the information from xml file but didn't see that in API you mentioned. 
https://api.govinfo.gov/packages/BILLSTATUS-116hr1839/summary?api_key=DEMO_KEY

Could you please check if there is any other API for this.

Regards,
Mani

**Comment by jonquandt** [comment]
@manimittal15 - sorry, I should have been clearer - the data is available via the BILLSTATUS xml, but you can track and access that xml file using the API - the summary links directly to the bulkdata.

The data is not available in the json summary.

**Comment by manimittal15** [comment]
@jonquandt Thank you very much Jon. This helps a lot.

**Comment by manimittal15** [comment]
@jonquandt : Thanks for addressing all my queries. Here is one thing I noticed in Billstatus XML files. 
Data related to Policy Area and legislative subjects are included in XML files few days after it is released. 
Is this the data issue or these fields are assigned later to the bills. I could not find any reason for this on congress.gov.

Thanks,
Mani

**Comment by jonquandt** [comment]
I believe this is a function of how the BILLSTATUS information is created. Staff at the Congressional Research Service review bill text and assign Policy Areas and Legislative subjects as part of the process. I believe it is not unusual for there to be some time between the original introduction of a bill and those values being added to the BILLSTATUS file

**Comment by manimittal15** [comment]
Sure Thanks.. That makes sense..
