### ISSUE TITLE
Missing current (116th) Congressional Directory data in the CDIR Collection?

### ISSUE THREAD

**Issue by jpelton-stroud** [usgpo/api#53]
The [Congressional Directory](https://www.govinfo.gov/help/cdir) site states:

> According to the U.S. Code (44 USC 721), the Congressional Directory is made available during the first session of each new Congress.

The most recent CD available, both on the site and via an API call on the CDIR collection, appears to be the 115th (2017-2018). Is this intended behavior? Is there is another GPO collection or package that contains listings for the 116th Congress (2019-2020) that I'm just not seeing?

**Comment by jonquandt** [comment]
Hi @jpelton-stroud -- This has not been added to the system yet. Once the volume has been printed, it will also be added to govinfo and made available via the API.

The [U.S. Code section](https://www.govinfo.gov/link/uscode/44/721?link-type=html&type=usc) indicates that this is to be printed and distributed "as early as practicable". My understanding is that information is still being compiled. 

The first edition of the CDIR for the 115th Congress was made available in June 2018.

**Comment by jpelton-stroud** [comment]
Thanks for the heads up, @jonquandt !  The "made available during the first session" language was a bit vague to me.

**Comment by jonquandt** [comment]
Agreed -- we've updated the help language to track a bit more closely with the USCODE section, though it's still doesn't give a definitive timeframe.
