### ISSUE TITLE
Title 41 Part number is trimmed

### ISSUE THREAD

**Issue by manimittal15** [usgpo/api#56]
Hi Team,

In Title 41 API we are not getting part number as mentioned in ecfr website. for eg Part 50-201 is mentioned as Part 50 in API.

Please refer below APIs for this issue:
https://api.govinfo.gov/packages/CFR-2019-title41-vol1/granules?offset=0&pageSize=1000&api_key=DEMO_KEY

https://api.govinfo.gov/packages/CFR-2019-title41-vol1/granules/CFR-2019-title41-vol1-part50-id33/summary?api_key=DEMO_KEY

Thanks,
Mani Mittal

**Comment by jonquandt** [comment]
@manimittal15  -- part 50 is very large and spread out across a number of granules. In the request you have indicated, part 50 is available in the following granules:

  "CFR-2019-title41-vol1-part50",
  "CFR-2019-title41-vol1-part50-id9",
  "CFR-2019-title41-vol1-part50-id9-toc-id10",
  "CFR-2019-title41-vol1-sec50-201-1",
  "CFR-2019-title41-vol1-sec50-201-2",
  "CFR-2019-title41-vol1-sec50-201-3",
  "CFR-2019-title41-vol1-sec50-201-4",
  "CFR-2019-title41-vol1-sec50-201-101",
  "CFR-2019-title41-vol1-sec50-201-102",
  "CFR-2019-title41-vol1-sec50-201-103",
  "CFR-2019-title41-vol1-sec50-201-104",
  "CFR-2019-title41-vol1-sec50-201-105",
  "CFR-2019-title41-vol1-sec50-201-201",
  "CFR-2019-title41-vol1-sec50-201-301",
  "CFR-2019-title41-vol1-sec50-201-501",
  "CFR-2019-title41-vol1-sec50-201-502",
  "CFR-2019-title41-vol1-sec50-201-601",
  "CFR-2019-title41-vol1-sec50-201-602",
  "CFR-2019-title41-vol1-sec50-201-603",
  "CFR-2019-title41-vol1-sec50-201-701",
  "CFR-2019-title41-vol1-sec50-201-1101",
  "CFR-2019-title41-vol1-sec50-201-1102",
  "CFR-2019-title41-vol1-sec50-201-1201",
  "CFR-2019-title41-vol1-sec50-201-1202",
  "CFR-2019-title41-vol1-sec50-201-1203",
  "CFR-2019-title41-vol1-part50-id33",
  "CFR-2019-title41-vol1-part50-id33-toc-id34",
  "CFR-2019-title41-vol1-part50-id33-subpartA",
  "CFR-2019-title41-vol1-sec50-202-1",
  "CFR-2019-title41-vol1-part50-id33-subpartB",
  "CFR-2019-title41-vol1-sec50-202-2",
  "CFR-2019-title41-vol1-sec50-202-3",
  "CFR-2019-title41-vol1-part50-id33-subpartC",
  "CFR-2019-title41-vol1-part50-id41",
  "CFR-2019-title41-vol1-part50-id41-toc-id42",
  "CFR-2019-title41-vol1-part50-id41-subpartA",
  "CFR-2019-title41-vol1-sec50-203-1",
  "CFR-2019-title41-vol1-sec50-203-2",
  "CFR-2019-title41-vol1-sec50-203-3",
  "CFR-2019-title41-vol1-sec50-203-4",
  "CFR-2019-title41-vol1-sec50-203-5",
  "CFR-2019-title41-vol1-sec50-203-6",
  "CFR-2019-title41-vol1-sec50-203-7",
  "CFR-2019-title41-vol1-sec50-203-8",
  "CFR-2019-title41-vol1-sec50-203-9",
  "CFR-2019-title41-vol1-sec50-203-10",
  "CFR-2019-title41-vol1-sec50-203-11",
  "CFR-2019-title41-vol1-sec50-203-12",
  "CFR-2019-title41-vol1-part50-id41-subpartB",
  "CFR-2019-title41-vol1-sec50-203-13",
  "CFR-2019-title41-vol1-sec50-203-14",
  "CFR-2019-title41-vol1-part50-id41-subpartC",
  "CFR-2019-title41-vol1-sec50-203-15",
  "CFR-2019-title41-vol1-sec50-203-16",
  "CFR-2019-title41-vol1-sec50-203-17",
  "CFR-2019-title41-vol1-sec50-203-18",
  "CFR-2019-title41-vol1-sec50-203-19",
  "CFR-2019-title41-vol1-sec50-203-20",
  "CFR-2019-title41-vol1-sec50-203-21",
  "CFR-2019-title41-vol1-sec50-203-22",
  "CFR-2019-title41-vol1-part50-id68",
  "CFR-2019-title41-vol1-part50-id68-toc-id69",
  "CFR-2019-title41-vol1-part50-id68-subpartA",
  "CFR-2019-title41-vol1-sec50-204-1",
  "CFR-2019-title41-vol1-sec50-204-1a",
  "CFR-2019-title41-vol1-part50-id68-subpartB",
  "CFR-2019-title41-vol1-sec50-204-2",
  "CFR-2019-title41-vol1-sec50-204-3",
  "CFR-2019-title41-vol1-sec50-204-4",
  "CFR-2019-title41-vol1-sec50-204-5",
  "CFR-2019-title41-vol1-sec50-204-6",
  "CFR-2019-title41-vol1-sec50-204-7",
  "CFR-2019-title41-vol1-sec50-204-8",
  "CFR-2019-title41-vol1-sec50-204-10",
  "CFR-2019-title41-vol1-part50-id68-subpartC",
  "CFR-2019-title41-vol1-sec50-204-20",
  "CFR-2019-title41-vol1-sec50-204-21",
  "CFR-2019-title41-vol1-sec50-204-22",
  "CFR-2019-title41-vol1-sec50-204-23",
  "CFR-2019-title41-vol1-sec50-204-24",
  "CFR-2019-title41-vol1-sec50-204-25",
  "CFR-2019-title41-vol1-sec50-204-26",
  "CFR-2019-title41-vol1-sec50-204-27",
  "CFR-2019-title41-vol1-sec50-204-28",
  "CFR-2019-title41-vol1-sec50-204-29",
  "CFR-2019-title41-vol1-sec50-204-30",
  "CFR-2019-title41-vol1-sec50-204-31",
  "CFR-2019-title41-vol1-sec50-204-32",
  "CFR-2019-title41-vol1-sec50-204-33",
  "CFR-2019-title41-vol1-sec50-204-34",
  "CFR-2019-title41-vol1-sec50-204-35",
  "CFR-2019-title41-vol1-sec50-204-36",
  "CFR-2019-title41-vol1-part50-id68-subpartD",
  "CFR-2019-title41-vol1-sec50-204-50",
  "CFR-2019-title41-vol1-sec50-204-65",
  "CFR-2019-title41-vol1-sec50-204-66",
  "CFR-2019-title41-vol1-sec50-204-67",
  "CFR-2019-title41-vol1-sec50-204-68",
  "CFR-2019-title41-vol1-sec50-204-69",
  "CFR-2019-title41-vol1-sec50-204-70",
  "CFR-2019-title41-vol1-sec50-204-71",
  "CFR-2019-title41-vol1-sec50-204-72",
  "CFR-2019-title41-vol1-part50-id68-subpartE",
  "CFR-2019-title41-vol1-sec50-204-75",
  "CFR-2019-title41-vol1-part50-id112",
  "CFR-2019-title41-vol1-part50-id112-toc-id113",
  "CFR-2019-title41-vol1-sec50-205-1",
  "CFR-2019-title41-vol1-sec50-205-2",
  "CFR-2019-title41-vol1-sec50-205-3",
  "CFR-2019-title41-vol1-sec50-205-4",
  "CFR-2019-title41-vol1-sec50-205-5",
  "CFR-2019-title41-vol1-sec50-205-6",
  "CFR-2019-title41-vol1-sec50-205-7",
  "CFR-2019-title41-vol1-sec50-205-8",
  "CFR-2019-title41-vol1-sec50-205-9",
  "CFR-2019-title41-vol1-sec50-205-10",
  "CFR-2019-title41-vol1-part50-id124",
  "CFR-2019-title41-vol1-part50-id124-toc-id125",
  "CFR-2019-title41-vol1-sec50-210-0",
  "CFR-2019-title41-vol1-sec50-210-1",
  "CFR-2019-title41-vol1-part50-id128",

In each granule summary, you can see the sections covered by the granule by looking at the `leafRange` element.

e.g.
https://api.govinfo.gov/packages/CFR-2019-title41-vol1/granules/CFR-2019-title41-vol1-part50-id9/summary
- this contains the entirety of part 50 section 201 (from 201.1-201.1203)

If you are looking for eCFR via the API, you would use the following collection code:

ECFR

Collections Service:
https://api.govinfo.gov/collections/ECFR/2019-12-16T00:00:00Z?offset=0&pageSize=100

package summary for eCFR title 41:
https://api.govinfo.gov/packages/ECFR-title41/summary

the bulkdata xml for title 41 is available at:
https://www.govinfo.gov/bulkdata/ECFR/title-41/ECFR-title41.xml

Within the xml, parts can be found by looking at the `DIV`s that have the `TYPE` attribute of `PART`

For example -- on line 92 of the bulkdata ECFR xml.
`<DIV5 N="50-1" NODE="41:1.2.1.1.1" TYPE="PART">`

I hope this is helpful.

**Comment by manimittal15** [comment]
Hi Jon, This is helpful.. Thanks a lot.
