### ISSUE TITLE
Clearly define valid paramaters 

### ISSUE THREAD

**Issue by chrisbabayans** [usgpo/api#59]
- collections
- collection
- packages
- packageId
- packageiD
- packageid
(find a better name for these three package id variations)
- summary 
- contentType
- granules
- granuleId
- startDate/endDate format defined

This will make it easier for people to send queries.

**Comment by jonquandt** [comment]
@chrisbabayans --

For `contentType`, are you asking for a complete list of possible values?

That would vary based on collection, and potentially over time. 

You can always see what content types are available in the /summary response for a given package. 

`packageId` and `granuleId` are both collection dependent as well. For most collections, you can get additional information on how these are constructed by looking at the help information available for the collection. 

Basics of govinfo URL structures:
https://www.govinfo.gov/help/url-structure

Concepts of collections, packages and granules:
https://www.govinfo.gov/help/whats-available#organization

List of collections with detailed help information:
https://www.govinfo.gov/help/whats-available

Package and granule ID patterns for individual collections:
https://www.govinfo.gov/help/`collection`#urls

example:
https://www.govinfo.gov/help/crec#urls

**Comment by chrisbabayans** [comment]
> @chrisbabayans --
> 
> For `contentType`, are you asking for a complete list of possible values?
> 
> That would vary based on collection, and potentially over time.
> 
> You can always see what content types are available in the /summary response for a given package.
> 
> `packageId` and `granuleId` are both collection dependent as well. For most collections, you can get additional information on how these are constructed by looking at the help information available for the collection.
> 
> Basics of govinfo URL structures:
> https://www.govinfo.gov/help/url-structure
> 
> Concepts of collections, packages and granules:
> https://www.govinfo.gov/help/whats-available#organization
> 
> List of collections with detailed help information:
> https://www.govinfo.gov/help/whats-available
> 
> Package and granule ID patterns for individual collections:
> [https://www.govinfo.gov/help/`collection`#urls](https://www.govinfo.gov/help/%60collection%60#urls)
> 
> example:
> https://www.govinfo.gov/help/crec#urls

Yes, I'm looking for a complete list of possible values, which I understand are collections.

https://www.govinfo.gov/help/whats-available satisfied that and more.

Thank you!

**Comment by jonquandt** [comment]
@chrisbabayans  - we have also made the changes to the api documentation on https://api.govinfo.gov/docs

I am putting an item on my to-do list to cleanup this repository's readme.

**Comment by chrisbabayans** [comment]
> @chrisbabayans - we have also made the changes to the api documentation on https://api.govinfo.gov/docs
> 
> I am putting an item on my to-do list to cleanup this repository's readme.

Wow, this is a major improvement! I greatly appreciate the efforts the team has put into this. Thank you all!!!!

**Comment by jonquandt** [comment]
@chrisbabayans  -- I'm glad that it helped!
