### ISSUE TITLE
call to collection CDOC is returning non CDOC items

### ISSUE THREAD

**Issue by relarson1** [usgpo/api#6]
when we make this api call 
https://api.govinfo.gov/collections/CDOC/2018-01-01T00:00:00Z?offset=2890&pageSize=10&api_key=XXXXXXXXXX

we are getting non CDOC documents
`
{"count":2985,"message":null,"nextPage":"https://api.govinfo.gov/collections/CDOC/2018-01-01T00:00:00Z?offset=2900&pageSize=10","previousPage":"https://api.govinfo.gov/collections/CDOC/2018-01-01T00:00:00Z?offset=2880&pageSize=10","packages":[{"packageId":"ERP-2015","lastModified":"2018-05-21T13:20:12Z","packageLink":"https://api.govinfo.gov/packages/ERP-2015/summary"},{"packageId":"GPO-CDOC-113sdoc25","lastModified":"2018-05-22T09:16:50Z","packageLink":"https://api.govinfo.gov/packages/GPO-CDOC-113sdoc25/summary"},{"packageId":"GPO-CDOC-115sdoc6","lastModified":"2018-05-31T14:16:16Z","packageLink":"https://api.govinfo.gov/packages/GPO-CDOC-115sdoc6/summary"},{"packageId":"ERP-2018","lastModified":"2018-05-21T13:20:15Z","packageLink":"https://api.govinfo.gov/packages/ERP-2018/summary"},{"packageId":"ERP-2008","lastModified":"2018-05-21T13:20:50Z","packageLink":"https://api.govinfo.gov/packages/ERP-2008/summary"},{"packageId":"HMAN-110","lastModified":"2018-05-21T14:12:58Z","packageLink":"https://api.govinfo.gov/packages/HMAN-110/summary"},{"packageId":"SMAN-106","lastModified":"2018-05-21T14:22:01Z","packageLink":"https://api.govinfo.gov/packages/SMAN-106/summary"},{"packageId":"SMAN-104","lastModified":"2018-05-21T14:21:48Z","packageLink":"https://api.govinfo.gov/packages/SMAN-104/summary"},{"packageId":"HMAN-115","lastModified":"2018-05-21T14:13:31Z","packageLink":"https://api.govinfo.gov/packages/HMAN-115/summary"},{"packageId":"GPO-CONAN-REV-2016","lastModified":"2018-05-22T04:38:06Z","packageLink":"https://api.govinfo.gov/packages/GPO-CONAN-REV-2016/summary"}]}'''`

**Comment by jonquandt** [comment]
@relarson1 Thanks for reporting this.

There are some documents that are considered both Congressional Documents as well as documents in other collections.

From the UI perspective, if you do the following search:
https://www.govinfo.gov/app/search/%7B%22query%22%3A%22collection%3Acdoc%22%2C%22offset%22%3A0%7D

You'll see that House and Senate Manual, Economic Reports of the President, and a selection of other documents are returned.

Generally speaking, these are documents that have House or Senate Document numbers. E.g. [Constitution Annotated](https://www.govinfo.gov/metadata/pkg/GPO-CONAN-REV-2016/mods.xml) is S. Doc 112-9.

these will also have ACCode values that include CDOC

From your perspective, would it be preferable to only include documents are CDOC-only?

**Comment by relarson1** [comment]
From our perspective currently we are currently only ingesting treaty documents so having a way to explicitly filter out only treaty type documents would be ideal.  Long term having an api call that would allow us to filter out each of those separate sub CDOC types would be great.

thanks,

**Comment by jonquandt** [comment]
@relarson1 - got it. so essentially, you'd be interested in seeing a list of documents equivalent to CDOCs that have the [tdoc docClass](https://www.govinfo.gov/app/search/%7B%22query%22%3A%22mods%3AdocClass%3Atdoc%22%2C%22offset%22%3A0%7D)

Long-term, I think the [search service](#1) is the right answer here, but we could look at adding some additional information to the collections response that might help you choose only the packages you need in the short term.

Would adding docClass and title to the collections response be helpful? E.g. for this [treaty doc](https://www.govinfo.gov/metadata/granule/CDOC-114tdoc13/CDOC-114tdoc13/mods.xml), something like this:

```json
        {
            "packageId": "CDOC-114tdoc13",
            "lastModified": "2018-05-21T12:49:23Z",
            "packageLink": "https://api.govinfo.gov/packages/CDOC-114tdoc13/summary",
            "title": "THE TREATIES WITH THE REPUBLIC OF KIRIBATI AND THE GOVERNMENT OF THE FEDERATED STATES OF MICRONESIA ON THE DELIMITATION OF MARITIME BOUNDARIES",           
            "docClass":"TDOC",
        },
```

I don't want to overload the collections responses with too much information, but this might be a couple of fields we could look to add.

**Comment by relarson1** [comment]
Yes that would be nice to have as long as we can call the api and filter based on it i.e. something like this:

`/collections/{collection}/docClass/TDOC/{startDate}`

or some other way of requesting just TDOCS that have changed since startDate.

**Comment by jonquandt** [comment]
@relarson1 - you can now request only treaty docs from the CDOC collections response by using the optional docClass parameter.

https://api.govinfo.gov/collections/CDOC/2018-01-01T00:00:00Z?offset=0&pageSize=10&docClass=TDOC&api_key=DEMO_KEY

This docClass parameter is available for all collections. Some collections have more useful docClasses than others -- for example, BILLS docClass correspond to Bill Types -- s, hr, hres, sconres, etc.
