### ISSUE TITLE
Errors when querying collections

### ISSUE THREAD

**Issue by aih** [usgpo/api#62]
Recently, when querying the `collections` API, using an API key, I've been getting `500` errors. This is not consistent and I'm not sure what triggers it, though it seems to happen more with queries close to the 10k document limit:

`https://api.govinfo.gov/collections/BILLS/2018-08-11T20:18:10Z/2019-08-11T19:20:10Z?offset=0&pageSize=10000&api_key=[API_KEY_HERE]`

**Comment by jonquandt** [comment]
@aih  -- apologies -- I just saw this. Are you still seeing errors? 

We recently adjusted the API to not allow requests with that large of a pageSize.

**Comment by ElusiveMind** [comment]
I am seeing this on the following URL

https://api.govinfo.gov/collections/BILLS/1994-01-01T20%3A18%3A10Z?pageSize=100&offset=10000&api_key=XXXXXXX

But not on

https://api.govinfo.gov/collections/BILLS/1994-01-01T20%3A18%3A10Z?pageSize=100&offset=9900&api_key=XXXXXXX

Is there an issue with offset size being 10000 or higher?
