### ISSUE TITLE
Rate limiting questions

### ISSUE THREAD

**Issue by ppourmand** [usgpo/api#69]
Hi! I have a couple questions about the api call limit; I can see on https://api.data.gov/docs/rate-limits/ here that it says 1000 per hour per api key but it mentions headers that should be returned where I can see my current usage (but I don't see them when I look at the return response of a govinfo API call) is that expected?

Also, is the 1000 per hour per key the current limit on this particular api? I know that's the default but wasn't sure if the govinfo limits are the same

thanks for your time!

**Comment by jonquandt** [comment]
@ppourmand  - the govinfo rate limits are significantly higher than that - currently ~18k requests/hour. I'll have to check to see about the rate limit display within the call though.

I see it when the DEMO_KEY is used, but not a standard key. Let me get back to you on that.

**Comment by jonquandt** [comment]
Issue should now be resolved. Please report back if you don't see the rate limits now. 

```
$ curl -I https://api.govinfo.gov/packages/CREC-2019-12-17/summary?api_key=################
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0HTTP/1.1 200 OK
Date: Wed, 09 Sep 2020 13:52:24 GMT
Content-Type: application/json
Connection: keep-alive
Vary: Accept-Encoding
X-RateLimit-Limit: 18000
X-RateLimit-Remaining: 17995
Strict-Transport-Security: max-age=31536000; preload
X-Frame-Options: SAMEORIGIN
Vary: Origin,Access-Control-Request-Method,Access-Control-Request-Headers
X-Content-Type-Options: nosniff
```

**Comment by ppourmand** [comment]
@jonquandt looks good; i see the headers now, thanks!

**Comment by christopherkang** [comment]
As an add-on to this @jonquandt could you describe whether there's a process to increase the limit? (Or, it'd also be helpful to learn how to navigate the bulk data repo programmatically)
