### ISSUE TITLE
Information about process from Voting Draft to publication in Federal Register

### ISSUE THREAD

**Issue by anuraggulati** [usgpo/api#70]
Hi there,
I was wondering someone might be able to help.
Where can I find the process/timeline around when a rule is made final and a voting draft pdf is available on the regulatory body's website v/s that rule appearing in the federal register?

For instance, Final Rule: Amendments to the Real-Time Public Reporting Requirements (Part 43), https://www.cftc.gov/media/4696/votingdraft091720Part43/download, are available on the CFTC's website and I wanted to know when they will be in the Fed Register by?

Thanks,
Anurag

**Comment by jonquandt** [comment]
@anuraggulati  - Hi, this isn't a technical question that we can answer here. You may wish to read more about the Unified Agenda on our help pages, which can point you towards some resources.

https://www.govinfo.gov/help/fr#unified-agenda

>The Unified Agenda of Federal Regulatory and Deregulatory Actions (Unified Agenda) provides uniform reporting on the actions administrative agencies plan to issue in the near and long term

But note that this is not necessarily an exhaustive listing of regulations under consideration, and that the dates are estimates, not firm deadlines.

I would highly recommend looking at the https://www.reginfo.gov site for the complete Unified Agenda and other information, which may be helpful.

**Comment by anuraggulati** [comment]
Thank you - I am not sure where to find this answer though - do you know if that best sits with the regulatory agency?
I have tried googling but cannot find "process from voting draft to publication in federal register" anywhere
"Voting Draft" not mentioned in the rulemaking process

**Comment by jonquandt** [comment]
You may want to look here as well.

https://www.federalregister.gov/uploads/2011/01/the_rulemaking_process.pdf 

or contact the [Office of the Federal Register](https://www.archives.gov/federal-register/contact.html), though you're likely correct that individual agencies would be the best source for timing on individual regulations..

**Comment by anuraggulati** [comment]
Thanks - I did look into rulemapking process before creating this, no joy - thank you so much!
