### ISSUE TITLE
Granules on 1-1-2021 showing up as 117th Congress instead of 116th

### ISSUE THREAD

**Issue by asebold** [usgpo/api#75]
January 1st 2021 was the last day of the 116th Congress, but metadata in the granules recognizes it as part of the 117th Congress. I noticed some tags are also missing BioGuide Ids, which my application relies on heavily. I imagine that other things might be missing too. 

Ex: https://api.govinfo.gov/packages/CREC-2021-01-01/granules/CREC-2021-01-01-pt1-PgS7995-7/mods?API_KEY=DEMO_KEY
```
<extension>
  <searchTitle>HAPPY NEW YEAR; Congressional Record Vol. 166, No. 224</searchTitle>
  <granuleClass>SENATE</granuleClass>
  <accessId>CREC-2021-01-01-pt1-PgS7995-7</accessId>
  <subGranuleClass>ALLOTHER</subGranuleClass>
  <pagePrefix>S</pagePrefix>
  <bookNumber>1</bookNumber>
  <chamber>SENATE</chamber>
  <granuleDate>2021-01-01</granuleDate>
  <congMember chamber="S" congress="117" role="SPEAKING">
    <name type="parsed">Mr. McCONNELL</name>
  </congMember>
</extension>
```
Notice the `congress` attribute on the `congMember` tag says 117. This tag is also missing the attribute `bioGuideId`.

**Comment by jonquandt** [comment]
Looking into this

**Comment by jonquandt** [comment]
@asebold  - This should now be resolved. 

```xml
<extension>
<searchTitle>HAPPY NEW YEAR; Congressional Record Vol. 166, No. 224</searchTitle>
<granuleClass>SENATE</granuleClass>
<accessId>CREC-2021-01-01-pt1-PgS7995-7</accessId>
<subGranuleClass>ALLOTHER</subGranuleClass>
<pagePrefix>S</pagePrefix>
<bookNumber>1</bookNumber>
<chamber>SENATE</chamber>
<granuleDate>2021-01-01</granuleDate>
<congMember authorityId="1395" bioGuideId="M000355" chamber="S" congress="116" gpoId="8254" party="R" role="SPEAKING" state="KY">
<name type="parsed">Mr. McCONNELL</name>
<name type="authority-fnf">Mitch McConnell</name>
<name type="authority-lnf">McConnell, Mitch</name>
</congMember>
</extension>
```

let me know if you see any other issues

**Comment by asebold** [comment]
Thanks @jonquandt! This is correct now. 

On a related note, I also can't get any CREC granules for this past Sunday. 
https://api.govinfo.gov/packages/CREC-2021-01-03/granules - just returns an empty array for me.
````
{
"count": 0,
"offset": 0,
"pageSize": 100,
"nextPage": null,
"previousPage": null,
"granules": []
}
````

**Comment by jonquandt** [comment]
@asebold - This is due to the fact that there are two CREC packages for that day - see CREC-2020-01-03-v166 and CREC-2020-01-03-v167.

https://api.govinfo.gov/packages/CREC-2021-01-03-v166/summary?api_key=DEMO_KEY
https://api.govinfo.gov/packages/CREC-2021-01-03-v167/summary?api_key=DEMO_KEY

Are you using the **collections** or **published** service to identify available CREC packages?

**Comment by asebold** [comment]
Ah, I've been generating the url on my own. I will switch to using collections.
