### ISSUE TITLE
api endpoint - /packages/{packageId}/granules not working as intended

### ISSUE THREAD

**Issue by gunnerwholelife** [usgpo/api#78]
I am trying to retrieve data for the api endpoint - /packages/{packageId}/granules

My curl looks like this -
`curl -X GET "https://api.govinfo.gov/packages/ECFR-title3/granules?offset=0&pageSize=10&api_key=<api-key>" -H  "accept: */*"`

Response -
`{"count":0,"offset":0,"pageSize":10,"nextPage":null,"previousPage":null,"granules":[]}`

I also used the interactive api but get couldn't get pass the required fields -
<img width="855" alt="govinpi-title-3-api-bug" src="https://user-images.githubusercontent.com/25061683/107721836-7e01bc00-6c92-11eb-8a30-59461e5c44ad.png">

Is this is a bug or I am doing something wrong ?

**Comment by jonquandt** [comment]
@gunnerwholelife  -- this is expected -- not all packages will have granules.

You would want to look at this package summary first:

https://api.govinfo.gov/packages/ECFR-title3/summary?api_key=DEMO_KEY

If the package summary does not display a granulesLink, then there are no granules available. 

A useful starting point:

https://api.govinfo.gov/collections?api_key=DEMO_KEY

This lists the collections that are available as well as the packageCount and granuleCount for each collection.

See [here](https://www.govinfo.gov/help/whats-available#organization) for a good explanation of collections, packages, and granules.

**Comment by gunnerwholelife** [comment]
@jonquandt Thanks a lot. Closing this issue.
