### ISSUE TITLE
Comprehensive list of subGranuleClass values for Congressional Record

### ISSUE THREAD

**Issue by jhanna71** [usgpo/api#84]
Hello, I am looking for a comprehensive list of subGranuleClass values for the Congressional Record. So far I have captured 83 distinct values but I was wondering if there were more for other categories such as treaties.

**Comment by jonquandt** [comment]
You can find additional items here: 
https://www.govinfo.gov/help/crec#metadata

Scroll down to "Section Metadata Values"

It looks like there are ~110 possible values, though it is possible that some have never been used.

Let me know if there is anything I can clarify.

**Comment by jhanna71** [comment]
Perfect. Thank you! 

Any word on when an XML format for Congressional Records might become available?

**Comment by jonquandt** [comment]
@jhanna71 - Making the Congressional Record available in XML is part of a major modernization effort within GPO known as XPub (formerly the Composition System Replacement program). I'm not aware of a specific timeframe for the Congressional Record being composed in XML at this time, but here's some additional information on XPub:
https://www.gpo.gov/who-we-are/news-media/news-and-press-releases/gpo-produces-final-report-for-the-select-committee-on-the-modernization-of-congress-with-new-digital-publishing-technology
