### ISSUE TITLE
billType values

### ISSUE THREAD

**Issue by RPoleshuck** [usgpo/api#85]
I am guessing at the meaning of bill types in the summary, shown below. Can someone point me to documentation or correct this map for me? Much thanks.

  var billTypeMap = {
      's': 'Senate bill',
      'sres': 'Senate resolution',
      'sr': '',
      'sjres': 'Senate joint resolution',
      'sconres': 'Senate concurrent resolution',
      'h': 'House bill',
      'hres': 'House resolution',
      'hr': '',
      'hjres': 'House joint resolution',
      'hconres': 'House concurrent resolution'
    };

**Comment by jonquandt** [comment]
@RPoleshuck 

You may want to check out our help information on Congressional Bills here -- while this has information regarding searches, much of it is also applicable to the data in the API. there is also a helpful list of bill versions on this page.

https://www.govinfo.gov/help/bills

updating your table. The `sr` and `h` bill types do not exist. House bills have a `docClass` of 'hr'

```javascript
var billTypeMap = {
's': 'Senate bill',
'sres': 'Senate resolution',
'sjres': 'Senate joint resolution',
'sconres': 'Senate concurrent resolution',
'hres': 'House resolution',
'hr': 'House bill',
'hjres': 'House joint resolution',
'hconres': 'House concurrent resolution'
};
