### ISSUE TITLE
500 occuring instead of a 404 for some urls

### ISSUE THREAD

**Issue by relarson1** [usgpo/api#9]
https://api.govinfo.gov/packages/CREC-2017-01-07/summary?api_key=<key>
Returns a 500 but should probably return a 404 instead since its just not an available item.
Our developers noticed that when putting in a date and going to the summary of a non existent package we get a 500 error instead of a 404.

Thanks,

**Comment by jonquandt** [comment]
@relarson1 -- summary requests for non-existent package ids now return the following:

```json
{
"message": "The requested resource does not exist. Please check back later or use the collections service to identify available content. If you know that the packageId and/or granuleId exists, check the /summary endpoint to see available renditions"
}
```

We are working on enhancing error messages across the API. more to come.
