### ISSUE TITLE
Granules have incorrect values for dateIssued

### ISSUE THREAD

**Issue by temujin-lampasa** [usgpo/api#90]
It seems that the **dateIssued** of all granules in a package is the same as the **dateIssued** of the entire package.

For instance:

Package: https://api.govinfo.gov/packages/USCOURTS-caed-2_17-mc-00157/summary?api_key=DEMO_KEY

This package has dateIssued = 2021-10-28

Granule: https://api.govinfo.gov/packages/USCOURTS-caed-2_17-mc-00157/granules/USCOURTS-caed-2_17-mc-00157-0/summary?api_key=DEMO_KEY

All the granules from 0 to 29 also have dateIssued = 2021-10-28.

This directly contradicts the dateIssued values in the MODS file: https://api.govinfo.gov/packages/USCOURTS-caed-2_17-mc-00157/mods?api_key=DEMO_KEY

**Comment by jonquandt** [comment]
Thank you for finding this issue. Looking into a fix.

**Comment by jonquandt** [comment]
@temujin-lampasa  This is now resolved.
