### ISSUE TITLE
HOB not listing legislative actions

### ISSUE THREAD

**Issue by MokeEire** [usgpo/api#92]
I think it's likely I am misunderstanding something here, but the History of Bills granules do not appear to list legislative actions.  Here is an example bill: [HR2295](https://www.govinfo.gov/content/pkg/HOB-2021/html/HOB-2021-hr2295.htm)

The MODS xml file has a field denoted `lastLegislativeAction`, but does not seem to contain information on the discrete actions pertaining to the bill.

How would one go about extracting the list of actions related to a given bill?

**Comment by jonquandt** [comment]
Hi -- you may be interested in looking at the Congressional Bill Status collectio, which provides machine-readable XML with additional information from the Library of Congress's Congressional Research Service. This is also available via the API.

Here's the resource:
https://api.govinfo.gov/packages/BILLSTATUS-117hr2295/summary?api_key=DEMO_KEY.

The billstatus xml is available from that location. We have a [separate rep](https://github.com/usgpo/bill-status)o with a [user guide](https://github.com/usgpo/bill-status/blob/master/BILLSTATUS-XML_User_User-Guide.md) for BILLSTATUS files. 

I hope this is helpful.
